/// A trait for accessing the md5 hash of an entry
pub trait Md5Hash {
    /// Returns the md5 hash of an entry
    ///
    /// If an implementation is generated by the macro, this value is `const` and computed at compile time
    fn md5(&self) -> &'static [u8; 16];
}
