/// A trait for accessing the sha1 hash of an entry
pub trait Sha1Hash {
    /// Returns the sha1 hash of an entry
    ///
    /// If an implementation is generated by the macro, this value is `const` and computed at compile time
    fn sha1(&self) -> &'static [u8; 20];
}
