/// A trait for accessing the sha2 224 hash of an entry
pub trait Sha2_224Hash {
    /// Returns the sha2 224 hash of an entry
    ///
    /// If an implementation is generated by the macro, this value is `const` and computed at compile time
    fn sha2_224(&self) -> &'static [u8; 28];
}

/// A trait for accessing the sha2 256 hash of an entry
pub trait Sha2_256Hash {
    /// Returns the sha2 256 hash of an entry
    ///
    /// If an implementation is generated by the macro, this value is `const` and computed at compile time
    fn sha2_256(&self) -> &'static [u8; 32];
}

/// A trait for accessing the sha2 384 hash of an entry
pub trait Sha2_384Hash {
    /// Returns the sha2 384 hash of an entry
    ///
    /// If an implementation is generated by the macro, this value is `const` and computed at compile time
    fn sha2_384(&self) -> &'static [u8; 48];
}

/// A trait for accessing the sha2 512 hash of an entry
pub trait Sha2_512Hash {
    /// Returns the sha2 512 hash of an entry
    ///
    /// If an implementation is generated by the macro, this value is `const` and computed at compile time
    fn sha2_512(&self) -> &'static [u8; 64];
}
