/// A trait for accessing the sha3 224 hash of an entry
pub trait Sha3_224Hash {
    /// Returns the sha3 224 hash of an entry
    ///
    /// If an implementation is generated by the macro, this value is `const` and computed at compile time
    fn sha3_224(&self) -> &'static [u8; 28];
}

/// A trait for accessing the sha3 256 hash of an entry
pub trait Sha3_256Hash {
    /// Returns the sha3 256 hash of an entry
    ///
    /// If an implementation is generated by the macro, this value is `const` and computed at compile time
    fn sha3_256(&self) -> &'static [u8; 32];
}

/// A trait for accessing the sha3 384 hash of an entry
pub trait Sha3_384Hash {
    /// Returns the sha3 384 hash of an entry
    ///
    /// If an implementation is generated by the macro, this value is `const` and computed at compile time
    fn sha3_384(&self) -> &'static [u8; 48];
}

/// A trait for accessing the sha3 512 hash of an entry
pub trait Sha3_512Hash {
    /// Returns the sha3 512 hash of an entry
    ///
    /// If an implementation is generated by the macro, this value is `const` and computed at compile time
    fn sha3_512(&self) -> &'static [u8; 64];
}
