name: Cargo Build & Test

on:
  push:
    branches: ["master"]
  pull_request_review:
    types: [submitted]
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    if: github.event_name == 'push' || (github.event_name == 'pull_request_review' && github.event.review.state == 'approved')
    name: Build and test
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, beta, nightly]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.toolchain }}
          components: "clippy"
      - run: cargo clippy --verbose --all-features -- -D warnings
      - run: cargo build --verbose --all-features
      - run: cargo test --verbose --all-features
        env:
          RUST_BACKTRACE: 1

  fmt:
    if: github.event_name == 'push' || (github.event_name == 'pull_request_review' && github.event.review.state == 'approved')
    name: Latest Dependencies
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: "rustfmt"
      - run: cargo fmt --check --verbose

  msrv:
    if: github.event_name == 'push' || (github.event_name == 'pull_request_review' && github.event.review.state == 'approved')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.81
      - run: cargo build --verbose --all-features
      - run: cargo test --verbose --all-features
        env:
          RUST_BACKTRACE: 1
