name: coverage

on:
  push:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  cover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest
      - run: cargo llvm-cov nextest --all-features --workspace --lcov --output-path lcov.info --ignore-filename-regex=".+/macros/src/test_helpers.rs"
      - uses: codecov/codecov-action@v3
        with:
          files: lcov.info
          fail_ci_if_error: true